#!/usr/bin/env CLI_TOOL=cli bash-cli-part
CLI_IMPORT=(
    "cli core type get-info"
)

cli::core::variable::get_info::help() {
    cat << EOF | cli::core::type::help
Command
    ${CLI_COMMAND[@]}
    
Summary
    Get the type of a variable.

Description
    Arguments \$1 is the name of the variable.

    Fail if the variable is undefined.
    
    The type is returned in REPLY.
    
    The following predicates are set:

        REPLY_CLI_CORE_VARIABLE_IS_INTEGER
        REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
        REPLY_CLI_CORE_VARIABLE_IS_STRING
        REPLY_CLI_CORE_VARIABLE_IS_SCALER
        REPLY_CLI_CORE_VARIABLE_IS_ARRAY
        REPLY_CLI_CORE_VARIABLE_IS_MAP
        REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
        REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
        REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED
EOF
}

cli::core::variable::get_info() {
    local NAME="${1:-}"
    [[ "${NAME}" ]] || cli::assert 'Missing variable name.'
    [[ "${NAME}" =~ ${CLI_REGEX_GLOBAL_NAME} ]] || cli::assert "Bad variable name '${NAME}'."

    local -n TYPE_REF="${NAME}__CLI_TYPE"
    if [[ ! -v TYPE_REF ]]; then
        return 1
    fi

    cli::core::type::get_info ${TYPE_REF}
    REPLY_CLI_CORE_VARIABLE_IS_INTEGER=${REPLY_CLI_CORE_TYPE_IS_INTEGER}
    REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN=${REPLY_CLI_CORE_TYPE_IS_BOOLEAN}
    REPLY_CLI_CORE_VARIABLE_IS_STRING=${REPLY_CLI_CORE_TYPE_IS_STRING}
    REPLY_CLI_CORE_VARIABLE_IS_SCALER=${REPLY_CLI_CORE_TYPE_IS_SCALER}
    REPLY_CLI_CORE_VARIABLE_IS_ARRAY=${REPLY_CLI_CORE_TYPE_IS_ARRAY}
    REPLY_CLI_CORE_VARIABLE_IS_MAP=${REPLY_CLI_CORE_TYPE_IS_MAP}
    REPLY_CLI_CORE_VARIABLE_IS_BUILTIN=${REPLY_CLI_CORE_TYPE_IS_BUILTIN}
    REPLY_CLI_CORE_VARIABLE_IS_MODIFIED=${REPLY_CLI_CORE_TYPE_IS_MODIFIED}
    REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED=${REPLY_CLI_CORE_TYPE_IS_USER_DEFINED}
}

cli::core::variable::get_info::self_test() {
    MY_UDT__CLI_TYPE=udt
    cli::core::variable::get_info MY_UDT
    [[ "${REPLY}" == 'udt' ]]
    [[ "${MAPFILE[*]}" == 'udt' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    ! $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    ! $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_STRING__CLI_TYPE=string
    cli::core::variable::get_info MY_STRING
    [[ "${REPLY}" == 'string' ]]
    [[ "${MAPFILE[*]}" == 'string' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    $REPLY_CLI_CORE_VARIABLE_IS_STRING
    $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_BOOLEAN__CLI_TYPE=boolean
    cli::core::variable::get_info MY_BOOLEAN
    [[ "${REPLY}" == 'boolean' ]]
    [[ "${MAPFILE[*]}" == 'boolean' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_INTEGER__CLI_TYPE=integer
    cli::core::variable::get_info MY_INTEGER
    [[ "${REPLY}" == 'integer' ]]
    [[ "${MAPFILE[*]}" == 'integer' ]]
    $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_MAP__CLI_TYPE=map
    cli::core::variable::get_info MY_MAP
    [[ "${REPLY}" == 'map' ]]
    [[ "${MAPFILE[*]}" == 'map' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    ! $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    $REPLY_CLI_CORE_VARIABLE_IS_MAP
    $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_ARRAY__CLI_TYPE=array
    cli::core::variable::get_info MY_ARRAY
    [[ "${REPLY}" == 'array' ]]
    [[ "${MAPFILE[*]}" == 'array' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    ! $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    ! $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_MAP_OF_UDT__CLI_TYPE="map_of udt"
    cli::core::variable::get_info MY_MAP_OF_UDT
    [[ "${REPLY}" == 'map_of udt' ]]
    [[ "${MAPFILE[*]}" == 'udt' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    ! $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    ! $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED

    MY_MAP_OF_MAP_OF_UDT__CLI_TYPE="map_of map_of udt"
    cli::core::variable::get_info MY_MAP_OF_MAP_OF_UDT
    [[ "${REPLY}" == 'map_of map_of udt' ]]
    [[ "${MAPFILE[*]}" == 'map_of udt' ]]
    ! $REPLY_CLI_CORE_VARIABLE_IS_INTEGER
    ! $REPLY_CLI_CORE_VARIABLE_IS_BOOLEAN
    ! $REPLY_CLI_CORE_VARIABLE_IS_STRING
    ! $REPLY_CLI_CORE_VARIABLE_IS_SCALER
    ! $REPLY_CLI_CORE_VARIABLE_IS_ARRAY
    ! $REPLY_CLI_CORE_VARIABLE_IS_MAP
    ! $REPLY_CLI_CORE_VARIABLE_IS_BUILTIN
    $REPLY_CLI_CORE_VARIABLE_IS_MODIFIED
    ! $REPLY_CLI_CORE_VARIABLE_IS_USER_DEFINED
}
