cli::process::get_info () 
{ 
    local PID="${1-${BASHPID}}";
    REPLY_CLI_PROCESS_ID=;
    REPLY_CLI_PROCESS_PARENT_ID=;
    REPLY_CLI_PROCESS_GROUP_ID=;
    REPLY_CLI_PROCESS_TERMINAL_ID=;
    REPLY_CLI_PROCESS_USER_ID=;
    REPLY_CLI_PROCESS_UTILIZATION=;
    REPLY_CLI_PROCESS_COMMAND=;
    REPLY_CLI_PROCESS_ARGS=;
    read REPLY_CLI_PROCESS_ID REPLY_CLI_PROCESS_PARENT_ID REPLY_CLI_PROCESS_GROUP_ID REPLY_CLI_PROCESS_TERMINAL_ID REPLY_CLI_PROCESS_USER_ID REPLY_CLI_PROCESS_UTILIZATION REPLY_CLI_PROCESS_COMMAND REPLY_CLI_PROCESS_ARGS < <(ps -p "${PID}" -o pid=,ppid=,pgid=,tname=,euid=,pcpu=,ucmd=,args=)
}
